// Generated by Wrangler on Mon Jan 23 2023 06:23:58 GMT+0900 (Japan Standard Time)
interface Env {
	rooms: DurableObjectNamespace;
	limiters: DurableObjectNamespace;
}
declare module "*.html" {
	const value: ArrayBuffer;
	export default value;
}
